import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { articles, achievements, eventIdeaCatalog, events, gallery, ideas, projects, resources, sigs, teamSections } from '@/data/content';
import { ArticleCard, Badge, EventCard, Icon, ProjectCard, SectionHeader } from '@/components/ui';
import { IdeaExplorer, LeaderboardPreview, ProjectExplorer } from '@/components/explorers';
import { SITE_DESCRIPTION, SITE_NAME, SITE_URL } from '@/lib/site';

type Params = { path: string[] };

const simplePages: Record<string, {eyebrow:string; title:string; body:string}> = {
  projects:{eyebrow:'PROJECTS',title:'Useful technology for campus and community.',body:'A data-driven portfolio of ideas, research, prototypes, pilots, and deployed systems. Status is explicit so the chapter never implies work is live when it is not.'},
  events:{eyebrow:'EVENTS',title:'Meet, learn, build, repeat.',body:'Workshops, talks, hackathons, study groups, research sessions, coding contests, open-source sprints, and community meetups.'},
  blog:{eyebrow:'ENGINEERING BLOG',title:'How we think about building.',body:'Technical tutorials, project writeups, research explainers, event recaps, open-source stories, and engineering deep dives.'},
  resources:{eyebrow:'RESOURCES',title:'A knowledge hub that grows with the chapter.',body:'Core subjects and engineering topics, ready for Markdown/MDX notes, curated learning paths, and practical references.'},
};

export function generateStaticParams(): Params[] {
  const routes: Params[] = [
    ...['about','projects','ideas','events','community','sigs','open-source','research','resources','blog','team','achievements','gallery','join','contribute','leaderboard','contact'].map(path=>({path:[path]})),
    ...projects.map(p=>({path:['projects',p.slug]})),
    ...events.map(e=>({path:['events',e.slug]})),
    ...articles.map(a=>({path:['blog',a.slug]})),
  ];
  return routes;
}
export const dynamicParams = false;

export async function generateMetadata({params}:{params:Promise<Params>}):Promise<Metadata>{
  const {path}=await params;
  const slug=path.join('/');
  const title = path.length===2 ? (path[0]==='projects' ? projects.find(x=>x.slug===path[1])?.title : path[0]==='events' ? events.find(x=>x.slug===path[1])?.title : articles.find(x=>x.slug===path[1])?.title) : ({ideas:'Ideas',leaderboard:'Leaderboard'}[path[0]] || simplePages[path[0]]?.title || 'ACM BIT Mesra');
  return { title, description:SITE_DESCRIPTION, alternates:{canonical:`${SITE_URL}/${slug}`}, openGraph:{title:`${title} — ${SITE_NAME}`,description:SITE_DESCRIPTION,url:`${SITE_URL}/${slug}`} };
}

function ShellPage({eyebrow,title,body,children}:{eyebrow:string;title:string;body:string;children:React.ReactNode}){
  return <><section className="page-hero"><div className="container"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{body}</p></div></section>{children}</>;
}

function About(){return <ShellPage eyebrow="ABOUT ACM BIT MESRA" title="A chapter built for the long run." body="A student-led technology community focused on useful systems, learning through practice, open source, and a culture where technical work can outlive a semester."><section className="section"><div className="container two-col"><div className="prose"><SectionHeader eyebrow="MISSION" title="Make building a shared student habit." body="Engineering is not only event activity—it is an ongoing practice."/><h2>What students do here</h2><p>Build software. Read papers. Run workshops. Solve problems. Review pull requests. Design systems. Document knowledge. Organize communities. Create technology that helps BIT Mesra and the wider community.</p><div className="callout">Documentation, maintainability, contribution paths, and ownership are part of the product—not post-demo cleanup.</div><h2>Why the chapter exists</h2><p>Student communities change quickly. A strong digital foundation helps preserve context, transfer ownership, and invite people into useful work without starting from zero.</p></div><aside><div className="metric-grid"><div className="metric"><strong>05</strong><span>Infrastructure projects</span></div><div className="metric"><strong>06</strong><span>SIG communities</span></div><div className="metric"><strong>12</strong><span>Resource tracks</span></div><div className="metric"><strong>∞</strong><span>Ideas welcome</span></div></div></aside></div></section></ShellPage>}

function Projects(){return <ShellPage eyebrow={simplePages.projects.eyebrow} title={simplePages.projects.title} body={simplePages.projects.body}><section className="page-shell"><div className="container"><ProjectExplorer projects={projects}/><div className="cta" style={{marginTop:28}}><div><div className="eyebrow">NEXT PROJECT</div><h3>Have a problem worth building for?</h3><p>Suggest a project in GitHub Issues. The community can refine the scope and recruit contributors.</p></div><a className="btn btn--accent" href="https://github.com/acm-bitmesra/acm-bitmesra.github.io/issues/new" target="_blank" rel="noreferrer">Suggest project <Icon name="external" size={15}/></a></div></div></section></ShellPage>}

function Events(){return <ShellPage eyebrow={simplePages.events.eyebrow} title={simplePages.events.title} body={simplePages.events.body}><section className="page-shell"><div className="container"><div className="event-list">{events.map(e=><EventCard key={e.slug} event={e}/>)}</div><div className="future-events"><div><div className="eyebrow">FUTURE EVENTS</div><h3>Bring the next event to life.</h3><p>Workshops, hackathons, talks, study groups, coding contests, research sessions, open-source sprints, and community meetups are all welcome.</p><div className="stack-row">{eventIdeaCatalog.map(x=><Badge key={x}>{x}</Badge>)}</div></div><a className="btn" href="https://github.com/acm-bitmesra/acm-bitmesra.github.io/issues/new" target="_blank" rel="noreferrer">Suggest event <Icon name="external" size={15}/></a></div></div></section></ShellPage>}

function Blog(){return <ShellPage eyebrow={simplePages.blog.eyebrow} title={simplePages.blog.title} body={simplePages.blog.body}><section className="page-shell"><div className="container cards-grid">{articles.map(a=><ArticleCard key={a.slug} article={a}/>)}</div></section></ShellPage>}
function Community(){return <ShellPage eyebrow="COMMUNITY" title="Many paths. One chapter." body="Beginners and experienced students can find a useful contribution path without waiting to become good enough."><section className="page-shell"><div className="container sig-grid">{sigs.map(s=><article className="sig-card" id={s.slug} key={s.slug}><div className="sig-card__label">SIG / {s.slug}</div><h3>{s.name}</h3><p>{s.description}</p><h4>Activities</h4><p>{s.activities.join(' · ')}</p><h4>Contribution</h4><div className="stack-row">{s.opportunities.map(o=><Badge key={o}>{o}</Badge>)}</div></article>)}</div></section></ShellPage>}
function SIGs(){return <ShellPage eyebrow="SPECIAL INTEREST GROUPS" title="Go deeper." body="Small communities for consistent practice, mentorship, focused projects, and shared learning."><section className="page-shell"><div className="container sig-grid">{sigs.map(s=><Link className="sig-card" href={`/community#${s.slug}`} key={s.slug}><div className="sig-card__label">SIG</div><h3>{s.name}</h3><p>{s.description}</p><span className="card-link">Explore group <Icon name="arrow" size={16}/></span></Link>)}</div></section></ShellPage>}
function OpenSource(){return <ShellPage eyebrow="OPEN SOURCE" title="Build in public." body="Real issues, real reviews, real collaboration, and artifacts future contributors can inspect."><section className="section"><div className="container"><SectionHeader eyebrow="CONTRIBUTION FUNNEL" title="From curious to contributor."/><div className="list">{['DISCOVER','FIND AN ISSUE','FORK','BUILD','PULL REQUEST','REVIEW','MERGE'].map((x,i)=><div className="list-row" key={x}><div className="label">0{i+1}</div><div style={{display:'flex',justifyContent:'space-between',gap:20}}><span>{x}</span>{i<6?<span className="mono">↓</span>:<Icon name="spark" size={16}/>}</div></div>)}</div></div></section></ShellPage>}
function Research(){return <ShellPage eyebrow="RESEARCH" title="Turn questions into evidence." body="Reading groups, experiments, student projects, faculty mentorship, and careful documentation create a place for technical research."><section className="page-shell"><div className="container cards-grid">{['AI','Computer Vision','NLP','Cybersecurity','Networks','Distributed Systems','Human-Computer Interaction','Software Engineering','Data Science'].map((x,i)=><div className="feature-card" key={x}><div className="sig-card__label">AREA / {String(i+1).padStart(2,'0')}</div><h3>{x}</h3><p>Projects, papers, experiments, and research opportunities can be added with verified authorship and outcomes.</p></div>)}</div></section></ShellPage>}
function Resources(){return <ShellPage eyebrow={simplePages.resources.eyebrow} title={simplePages.resources.title} body={simplePages.resources.body}><section className="page-shell"><div className="container resource-grid">{resources.map(r=><article className="resource-card" key={r.title}><div className="category">{r.category}</div><h3>{r.title}</h3><p>{r.description}</p><span className="card-link">Open track →</span></article>)}</div></section></ShellPage>}

function Ideas(){return <ShellPage eyebrow="IDEAS" title="A backlog for things we could build together." body="These are possible projects, events, research directions, and community experiments. Nothing here is presented as already deployed. Pick one, discuss it, improve it, and open an issue or community thread to gather people."><section className="page-shell"><div className="container"><IdeaExplorer ideas={ideas}/><div className="cta" style={{marginTop:28}}><div><div className="eyebrow">OPEN INVITATION</div><h3>Have a better idea?</h3><p>Come to GitHub Issues or the ACM community and suggest a project, event, workshop, research direction, or improvement.</p></div><div className="hero-actions" style={{marginTop:0}}><a className="btn btn--accent" href="https://github.com/acm-bitmesra/acm-bitmesra.github.io/issues/new" target="_blank" rel="noreferrer">Open an issue <Icon name="external" size={15}/></a><Link href="/community" className="btn">Find a community</Link></div></div></div></section></ShellPage>}

function Leaderboard(){return <ShellPage eyebrow="LEADERBOARD" title="Contribution rankings are coming soon." body="The chapter plans to make contribution visible without reducing community work to vanity metrics. Scoring rules, data sources, privacy boundaries, and recognition mechanics will be published before rankings go live."><section className="page-shell"><div className="container"><LeaderboardPreview/><div className="list" style={{marginTop:28}}>{['Merged pull requests','Issue contributions','Code reviews','Project work','Documentation and content','Event and community contributions'].map((x,i)=><div className="list-row" key={x}><div className="label">0{i+1}</div><div><strong>{x}</strong><p style={{color:'var(--muted)',margin:'5px 0 0'}}>Planned metric — no live score yet.</p></div></div>)}</div></div></section></ShellPage>}

function Team(){return <ShellPage eyebrow="TEAM" title="People make the chapter." body="Names, roles, links, terms, and alumni history should be added only from verified chapter information."><section className="page-shell"><div className="container timeline">{teamSections.map((x,i)=><div className="timeline-item" key={x}><div className="timeline-year">{String(i+1).padStart(2,'0')}</div><div><h3 style={{margin:'0 0 7px'}}>{x}</h3><p style={{margin:0,color:'var(--muted)'}}>Roster intentionally omitted until verified.</p></div></div>)}</div></section></ShellPage>}
function Achievements(){return <ShellPage eyebrow="ACHIEVEMENTS" title="Keep the record honest." body="Use verified milestones: wins, awards, publications, open-source contributions, major projects, workshops, and community outcomes."><section className="page-shell"><div className="container timeline">{achievements.map(x=><div className="timeline-item" key={x.title}><div className="timeline-year">{x.year}</div><div><h3 style={{margin:'0 0 7px'}}>{x.title}</h3><p style={{margin:0,color:'var(--muted)'}}>{x.description}</p></div></div>)}</div></section></ShellPage>}
function Gallery(){return <ShellPage eyebrow="GALLERY" title="Show the work. Show the people." body="A visual archive for events, workshops, hackathons, teams, projects, and community moments."><section className="page-shell"><div className="container gallery-grid">{gallery.map(g=><div className="gallery-card" key={g.title}><div className="gallery-card__label">{g.label}</div><h3>{g.title}</h3><p>{g.meta}</p></div>)}</div></section></ShellPage>}
function Join(){const paths:[string,string][]=[['Beginner','Learn the basics and make a first small contribution.'],['Developer','Build products, campus systems, demos, and reusable infrastructure.'],['Designer','Shape interfaces, design systems, docs, and visual communication.'],['Researcher','Join reading groups, experiments, and faculty-led work.'],['Competitive Programmer','Practice DSA, contests, and interview-style problem solving.'],['Organizer','Run workshops, study groups, hackathons, and community meetups.'],['Open Source Contributor','Triage issues, write docs, review pull requests, and maintain quality.']];return <ShellPage eyebrow="JOIN ACM" title="You don't need to be an expert." body="Join to build, learn, teach, research, design, organize, or contribute. Start where you are."><section className="page-shell"><div className="container"><div className="cards-grid">{paths.map(([t,b])=><div className="feature-card" key={t}><div className="sig-card__label">PATH</div><h3>{t}</h3><p>{b}</p></div>)}</div><div style={{marginTop:24}} className="cta"><div><h3>Start by showing up.</h3><p>Events, SIGs, projects, and contribution workflows are entry points.</p></div><Link href="/events" className="btn btn--accent">See events <Icon name="arrow" size={16}/></Link></div></div></section></ShellPage>}
function Contribute(){return <ShellPage eyebrow="CONTRIBUTE" title="Ideas become projects when people build them." body="Contribution is broader than code: designers, writers, testers, researchers, event volunteers, and maintainers all matter."><section className="page-shell"><div className="container resource-grid">{['Code','Design','Documentation','Content','Research','Events','Testing','Infrastructure','Ideas'].map(x=><div className="resource-card" key={x}><div className="category">CONTRIBUTE</div><h3>{x}</h3><p>Find or create a focused contribution and leave it better documented than you found it.</p></div>)}</div></section></ShellPage>}
function Contact(){return <ShellPage eyebrow="CONTACT" title="Build something with us." body="Use the repository for contribution work, and add official chapter contact channels once they are confirmed."><section className="page-shell"><div className="container two-col"><div className="feature-card"><div className="eyebrow">GITHUB</div><h3>Chapter infrastructure</h3><p>The public website repository is the starting point for code, documentation, and issues.</p><a href="https://github.com/SH20RAJ/acm-bitmesra.github.io" target="_blank" rel="noreferrer" className="btn">Open GitHub <Icon name="github" size={15}/></a></div><div className="feature-card"><div className="eyebrow">CHAPTER</div><h3>BIT Mesra · Ranchi</h3><p>Official email, advisor contact, social accounts, and registration links should be published only after verification.</p></div></div></section></ShellPage>}

function ProjectDetail({slug}:{slug:string}){const p=projects.find(x=>x.slug===slug);if(!p)return notFound();return <ShellPage eyebrow={`PROJECT ${p.number} · ${p.status}`} title={p.title} body={p.short}><section className="page-shell"><div className="container two-col"><div className="prose"><SectionHeader eyebrow="PROJECT OVERVIEW" title="Problem → solution → evidence."/><h2>Problem</h2><p>{p.problem}</p><h2>Why it matters</h2><p>{p.goal}</p><h2>Proposed solution</h2><p>The architecture is intentionally modular so future contributors can add services, dashboards, notifications, and integrations without rewriting the public chapter site.</p><h2>Features</h2><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><h2>Current status</h2><p><Badge tone="accent">{p.status}</Badge> This label describes the current content status, not deployment. No live deployment is claimed.</p></div><aside><div className="feature-card"><div className="eyebrow">TECHNOLOGY</div><h3>Suggested stack</h3><div className="stack-row">{p.stack.map(s=><Badge key={s}>{s}</Badge>)}</div><h4 style={{marginTop:30}}>Future architecture</h4><p style={{color:'var(--muted)'}}>Frontend → API → Authentication → Database → Services</p><div className="hero-actions" style={{marginTop:24}}><Link className="btn btn--accent" href="/contribute">How to contribute <Icon name="arrow" size={16}/></Link><a className="btn" href="https://github.com/acm-bitmesra/acm-bitmesra.github.io/issues/new" target="_blank" rel="noreferrer">Discuss on GitHub <Icon name="external" size={15}/></a></div></div></aside></div></section></ShellPage>}
function EventDetail({slug}:{slug:string}){const e=events.find(x=>x.slug===slug);if(!e)return notFound();return <ShellPage eyebrow={e.category.toUpperCase()} title={e.title} body={e.description}><section className="page-shell"><div className="container two-col"><div className="prose"><h2>Event details</h2><div className="list"><div className="list-row"><div className="label">Date</div><div>{e.date}</div></div><div className="list-row"><div className="label">Time</div><div>{e.time}</div></div><div className="list-row"><div className="label">Venue</div><div>{e.venue}</div></div><div className="list-row"><div className="label">Status</div><div><Badge tone="accent">{e.status}</Badge></div></div></div></div><aside><div className="feature-card"><div className="eyebrow">TAGS</div><div className="stack-row">{e.tags.map(t=><Badge key={t}>{t}</Badge>)}</div><p style={{color:'var(--muted)',marginTop:24}}>Registration, resources, photos, recordings, and GitHub links can be attached when verified for the event.</p><Link className="btn" href="/events">All events <Icon name="arrow" size={16}/></Link></div></aside></div></section></ShellPage>}
function ArticleDetail({slug}:{slug:string}){const a=articles.find(x=>x.slug===slug);if(!a)return notFound();return <ShellPage eyebrow={a.tags.join(' · ').toUpperCase()} title={a.title} body={a.description}><section className="page-shell"><div className="container two-col"><article className="prose"><div className="article-card__meta"><span>{a.date}</span><span>{a.readingTime}</span></div><h2>Context</h2><p>Good chapter infrastructure compounds. A decision that is easy to understand today is easier for the next contributor to review, improve, and maintain.</p><h2>What to practice</h2><p>Start from the smallest useful artifact, write down the decision, link the evidence, and make the next contribution obvious.</p><div className="callout">A technical community becomes stronger when its knowledge is inspectable: code, issues, documentation, examples, and reviews all leave context behind.</div><h2>Related work</h2><div className="stack-row">{a.tags.map(t=><Badge key={t}>{t}</Badge>)}</div></article><aside><SectionHeader eyebrow="MORE" title="Keep exploring."/><div className="event-list">{articles.filter(x=>x.slug!==a.slug).slice(0,2).map(x=><ArticleCard key={x.slug} article={x}/>)}</div></aside></div></section></ShellPage>}

export default async function CatchAll({params}:{params:Promise<Params>}){
  const {path}=await params;
  if(path.length===1){switch(path[0]){case'about':return <About/>;case'projects':return <Projects/>;case'ideas':return <Ideas/>;case'events':return <Events/>;case'community':return <Community/>;case'sigs':return <SIGs/>;case'open-source':return <OpenSource/>;case'research':return <Research/>;case'resources':return <Resources/>;case'blog':return <Blog/>;case'team':return <Team/>;case'achievements':return <Achievements/>;case'gallery':return <Gallery/>;case'join':return <Join/>;case'contribute':return <Contribute/>;case'leaderboard':return <Leaderboard/>;case'contact':return <Contact/>;default:return notFound()}}
  if(path.length===2){if(path[0]==='projects')return <ProjectDetail slug={path[1]}/>;if(path[0]==='events')return <EventDetail slug={path[1]}/>;if(path[0]==='blog')return <ArticleDetail slug={path[1]}/>;}
  return notFound();
}
