'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import type { Project, EventItem, Article } from '@/data/content';
import { nav } from '@/data/content';

export type IconName='arrow'|'github'|'menu'|'close'|'external'|'spark'|'code'|'book'|'users';
export function Icon({name,size=18}:{name:IconName;size?:number}){const c={width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const,'aria-hidden':true};switch(name){case'arrow':return <svg {...c}><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></svg>;case'github':return <svg {...c}><path d="M15 22v-4a3 3 0 0 0-3-3H8a3 3 0 0 1-3-3"/><path d="M8 15c-2.5 0-4-1.2-4-3"/><path d="M7 9c-2-2.5-1-6 2-7 1.2.9 4.8.9 6 0 3 1 4 4.5 2 7"/><path d="M17 15c2.5 0 4-1.2 4-3"/><path d="M12 15v7"/></svg>;case'menu':return <svg {...c}><path d="M4 7h16M4 12h16M4 17h16"/></svg>;case'close':return <svg {...c}><path d="m6 6 12 12M18 6 6 18"/></svg>;case'external':return <svg {...c}><path d="M14 5h5v5"/><path d="M19 5 10 14"/><path d="M19 13v5a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5"/></svg>;case'spark':return <svg {...c}><path d="m12 2 1.7 6.3L20 10l-6.3 1.7L12 18l-1.7-6.3L4 10l6.3-1.7L12 2Z"/></svg>;case'code':return <svg {...c}><path d="m8 9-3 3 3 3M16 9l3 3-3 3M14 5l-4 14"/></svg>;case'book':return <svg {...c}><path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v17H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M4 4.5v17"/></svg>;case'users':return <svg {...c}><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0"/><circle cx="17" cy="9" r="2"/><path d="M16 14.5a5 5 0 0 1 5 5"/></svg>;}}
export function Badge({children,tone='default'}:{children:React.ReactNode;tone?:'default'|'accent'|'muted'}){return <span className={'badge badge--'+tone}>{children}</span>}
export function SectionHeader({eyebrow,title,body,align='left'}:{eyebrow:string;title:string;body?:string;align?:'left'|'center'}){return <div className={'section-header '+(align==='center'?'section-header--center':'')}><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{body&&<p>{body}</p>}</div>}
export function ProjectCard({project}:{project:Project}){return <Link href={'/projects/'+project.slug} className="project-card"><div className="project-card__top"><span className="mono">PROJECT {project.number}</span><Badge tone={project.status==='IDEA'?'muted':'accent'}>{project.status}</Badge></div><div className="project-card__visual"><span>{project.accent}</span><span className="project-card__grid"/></div><h3>{project.title}</h3><p>{project.short}</p><span className="card-link">Explore project <Icon name="arrow" size={16}/></span></Link>}
export function EventCard({event}:{event:EventItem}){const d=new Date(event.date);return <Link href={'/events/'+event.slug} className="event-card"><div className="event-card__date"><span>{d.toLocaleDateString('en-IN',{day:'2-digit'})}</span><small>{d.toLocaleDateString('en-IN',{month:'short'}).toUpperCase()}</small></div><div><div className="event-card__meta"><Badge tone="accent">{event.category}</Badge><span className="mono">{event.time}</span></div><h3>{event.title}</h3><p>{event.description}</p><span className="card-link">View event <Icon name="arrow" size={16}/></span></div></Link>}
export function ArticleCard({article}:{article:Article}){return <Link href={'/blog/'+article.slug} className="article-card"><div className="article-card__cover"><span className="mono">{article.tags[0].toUpperCase()}</span><strong>ACM</strong></div><div className="article-card__meta"><span>{article.date}</span><span>{article.readingTime}</span></div><h3>{article.title}</h3><p>{article.description}</p><span className="card-link">Read article <Icon name="arrow" size={16}/></span></Link>}
export function Navbar(){const[open,setOpen]=useState(false);const pathname=usePathname();return <header className="site-header"><div className="container nav-wrap"><Link href="/" className="brand" onClick={()=>setOpen(false)}><span className="brand-mark">A</span><span><strong>ACM</strong><small>BIT MESRA</small></span></Link><nav className={'nav-links '+(open?'nav-links--open':'')} aria-label="Primary navigation">{nav.map(i=><Link href={i.href} key={i.href} className={'nav-link '+(pathname===i.href||pathname?.startsWith(i.href+'/')?'is-active':'')} aria-current={pathname===i.href?'page':undefined} onClick={()=>setOpen(false)}>{i.label}</Link>)}<Link href="/join" className="nav-cta" onClick={()=>setOpen(false)}>Join ACM <Icon name="arrow" size={15}/></Link></nav><button type="button" className="menu-btn" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Icon name={open?'close':'menu'}/></button></div></header>}
export function Footer(){return <footer className="footer"><div className="container footer-grid"><div><div className="brand brand--footer"><span className="brand-mark">A</span><span><strong>ACM</strong><small>BIT MESRA</small></span></div><p className="footer-note">BUILD. LEARN. SHIP.<br/>Student-led technology, research, and open source at BIT Mesra.</p></div><div><div className="footer-label">Explore</div><div className="footer-links"><Link href="/projects">Projects</Link><Link href="/ideas">Ideas</Link><Link href="/events">Events</Link><Link href="/open-source">Open Source</Link><Link href="/research">Research</Link></div></div><div><div className="footer-label">Participate</div><div className="footer-links"><Link href="/join">Join ACM</Link><Link href="/contribute">Contribute</Link><Link href="/community">Community</Link><Link href="/leaderboard">Leaderboard</Link><Link href="/contact">Contact</Link></div></div><div><div className="footer-label">Repository</div><a className="footer-github" href="https://github.com/acm-bitmesra/acm-bitmesra.github.io" target="_blank" rel="noreferrer"><Icon name="github" size={16}/> GitHub <Icon name="external" size={14}/></a><a className="footer-github" href="https://github.com/acm-bitmesra/acm-bitmesra.github.io/issues" target="_blank" rel="noreferrer"><span aria-hidden="true">#</span> Issues <Icon name="external" size={14}/></a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} ACM BIT Mesra</span><span className="mono">STUDENT CHAPTER · RANCHI</span></div></footer>}
export function Shell({children}:{children:React.ReactNode}){return <><Navbar/><div id="main">{children}</div><Footer/></>}
